import type { Metadata } from "next";
import { Roboto, Bebas_Neue } from "next/font/google";
import "./globals.css";

const robotRegular = Roboto({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-roboto-regular",
});

const BebasNeue = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bebas-neue",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotRegular.className} ${BebasNeue.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
